//
// Generated file, do not edit! Created by opp_msgc 4.2 from UDPPingMsg.msg.
//

#ifndef _UDPPINGMSG_M_H_
#define _UDPPINGMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "INETDefs.h"
// }}



/**
 * Class generated from <tt>UDPPingMsg.msg</tt> by opp_msgc.
 * <pre>
 * packet UDPPingMsg
 * {
 *     int counter;
 *     bool isRequest = true;
 * }
 * </pre>
 */
class UDPPingMsg : public ::cPacket
{
  protected:
    int counter_var;
    bool isRequest_var;

  private:
    void copy(const UDPPingMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UDPPingMsg&);

  public:
    UDPPingMsg(const char *name=NULL, int kind=0);
    UDPPingMsg(const UDPPingMsg& other);
    virtual ~UDPPingMsg();
    UDPPingMsg& operator=(const UDPPingMsg& other);
    virtual UDPPingMsg *dup() const {return new UDPPingMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getCounter() const;
    virtual void setCounter(int counter);
    virtual bool getIsRequest() const;
    virtual void setIsRequest(bool isRequest);
};

inline void doPacking(cCommBuffer *b, UDPPingMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, UDPPingMsg& obj) {obj.parsimUnpack(b);}


#endif // _UDPPINGMSG_M_H_
